title: Samuele Punzo
email: samuelepunzo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Master's Student in AI at the University of Amsterdam.
  Researcher in Mechanistic Interpretability and Computational Health.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://SamuelePunzo.github.io" # the base hostname & protocol for your site
github_username: SamuelePunzo
linkedin_username: samuele-punzo

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Footer content
footer_content: >-
  Â© 2025 Samuele Punzo. Honors Graduate in Computer Science, University of Pisa.
  Currently researching AI at UvA.
